name: Build & Test

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

env:
  TOKENKEY: ${{ secrets.TOKENKEY }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
     - name: Setup NuGet
       uses: NuGet/setup-nuget@v1.0.6
        with:
       nuget-version: latest
     - name: Restore NuGet packages
      run: nuget restore
    - name: Restore dependencies
      run: dotnet restore ./Eucyon-Tribes/Eucyon-Tribes.sln
    - name: Build
      run: dotnet build --no-restore ./Eucyon-Tribes/Eucyon-Tribes.sln
    - name: Test
      run: dotnet test --no-build --verbosity minimal ./Eucyon-Tribes/
