name: Build & Test

on:
   push:
    branches: [ "master" ]
   pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Eucyon-Tribes/Eucyon-Tribes.sln
    - name: Build
      run: dotnet build --no-restore ./Eucyon-Tribes/Eucyon-Tribes.sln
    - name: Test
      env:
        TokenGenerationKey: "THE MOST SECRET SECRET USED TO SIGN AND VERIFY JWT TOKENS, THAT IS DEFINITELY VERY SECURE"
        TRIBES_GAMETICK_LEN: 60
        ARMY_SIZE_LIMIT: 12
      run: dotnet test --no-build --verbosity normal ./Eucyon-Tribes/Eucyon-Tribes.sln
