name: .NET

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

env:
  TOKENKEY: ${{ secrets.TOKENKEY }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 
          5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./Eucyon-Tribes
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./Eucyon-Tribes
    - name: Test
      run: dotnet test --no-build --verbosity minimal ./Eucyon-Tribes
