name: Build & Test

on:
   push:
    branches: [ "master" ]
   pull_request:
    branches: [ "master" ]
    
env:
  TokenGenerationKey: b7595051-3f87-49e4-8f55-9fe1dfe724d1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Eucyon-Tribes/Eucyon-Tribes.sln
    - name: Build
      run: dotnet build --no-restore ./Eucyon-Tribes/Eucyon-Tribes.sln
    - name: Test
      run: dotnet test --no-build --verbosity minimal ./Eucyon-Tribes/
