name: Build & Test

on:
   push:
    branches: [ "master" ]
   pull_request:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Eucyon-Tribes/Eucyon-Tribes.sln
    - name: Build
      run: dotnet build --no-restore ./Eucyon-Tribes/Eucyon-Tribes.sln
    - name: Test
      env:
        TokenGenerationKey: ${{ secrets.TOKENGENERATIONKEY }}
        TRIBES_GAMETICK_LEN: ${{ secrets.TRIBES_GAMETICK_LEN }}
        ARMY_SIZE_LIMIT: ${{ secrets.ARMY_SIZE_LIMIT }}
      run: dotnet test --no-build --verbosity minimal ./Eucyon-Tribes/
